# @see https://devdocs.prestashop-project.org/9/modules/concepts/controllers/admin-controllers/#how-to-map-an-action-of-your-controller-to-a-uri
ps_controller_tabs_configure:
    path: /configure-tabs
    methods: [GET]
    defaults:
        _controller: 'PrestaShop\Module\ExtraShippingLabels\Controller\Admin\ConfigureController::indexAction'
        _legacy_controller: 'AdminExtraShippingLabelsConfigure'
        _legacy_link: 'AdminExtraShippingLabelsConfigure'

ps_controller_tabs_minimalist:
    path: /configure-tabs/minimalist
    methods: [GET]
    defaults:
        _controller: 'PrestaShop\Module\ExtraShippingLabels\Controller\Admin\MinimalistController::indexAction'

ps_controller_tabs_secured:
    path: /configure-tabs/secured
    methods: [GET]
    defaults:
        _controller: 'PrestaShop\Module\ExtraShippingLabels\Controller\Admin\SecuredController::indexAction'
        _legacy_controller: 'AdminExtraShippingLabelsSecured'

ps_controller_tabs_manual_tab:
    path: /configure-tabs/manual_tab
    methods: [GET]
    defaults:
        _controller: 'PrestaShop\Module\ExtraShippingLabels\Controller\Admin\ManualTabController::indexAction'


ps_extrashippinglabels_labels_index:
    path: /extrashippinglabels/labels
    methods: [GET, POST]
    defaults:
        _controller: 'PrestaShop\Module\ExtraShippingLabels\Controller\Admin\ShippingLabelController::indexAction'
        _legacy_controller: 'AdminShippingLabel'
        _legacy_link: 'AdminShippingLabel'

ps_extrashippinglabels_labels_search:
    path: /extrashippinglabels/labels/search
    methods: [POST]
    defaults:
        _controller: 'PrestaShop\Module\ExtraShippingLabels\Controller\Admin\ShippingLabelController::searchAction'
        _legacy_controller: 'AdminShippingLabel'
        _legacy_link: 'AdminShippingLabel'

ps_extrashippinglabels_labels_delete:
    path: /extrashippinglabels/labels/{shippingLabelId}/delete
    methods: [POST]
    defaults:
        _controller: 'PrestaShop\Module\ExtraShippingLabels\Controller\Admin\ShippingLabelController::deleteAction'
        _legacy_controller: 'AdminShippingLabel'
        _legacy_link: 'AdminShippingLabel'
    requirements:
        shippingLabelId: \d+

ps_extrashippinglabels_labels_bulk_delete:
    path: /extrashippinglabels/labels/bulk-delete
    methods: [POST]
    defaults:
        _controller: 'PrestaShop\Module\ExtraShippingLabels\Controller\Admin\ShippingLabelController::bulkDeleteAction'
        _legacy_controller: 'AdminShippingLabel'
        _legacy_link: 'AdminShippingLabel'